import { Attraction, Park, Land } from './types';

export const USERS_LIST = [
  "Alexandre", "Apolline", "Benoît", "Camille", "Celeste", "Cécile",
  "Elisabeth", "Igor", "Izza", "Hamza", "Jean", "Leo", "Lucas",
  "Margot", "Marie", "Maxime", "Mina", "Nicolas", "Pernelle",
  "Raphaël", "Romain", "Ruben", "Sathasivam", "Tiphaine", "William"
];

export const WEATHER_FORECAST = [
  { hour: '09h', temp: '2°', condition: 'cloudy', icon: 'cloud' },
  { hour: '10h', temp: '3°', condition: 'cloudy', icon: 'cloud' },
  { hour: '11h', temp: '4°', condition: 'sunny', icon: 'sun' },
  { hour: '12h', temp: '6°', condition: 'sunny', icon: 'sun' },
  { hour: '13h', temp: '7°', condition: 'partly-cloudy', icon: 'cloud-sun' },
  { hour: '14h', temp: '7°', condition: 'partly-cloudy', icon: 'cloud-sun' },
  { hour: '15h', temp: '6°', condition: 'rainy', icon: 'cloud-rain' },
  { hour: '16h', temp: '5°', condition: 'rainy', icon: 'cloud-rain' },
  { hour: '17h', temp: '4°', condition: 'cloudy', icon: 'cloud' },
  { hour: '18h', temp: '3°', condition: 'clear', icon: 'moon' },
  { hour: '19h', temp: '2°', condition: 'clear', icon: 'moon' },
];

export const ATTRACTIONS: Attraction[] = [
  // --- MAIN STREET U.S.A. ---
  { 
    id: 'dlp_1', 
    name: 'Disneyland Railroad', 
    park: Park.DISNEYLAND, 
    land: Land.MAIN_STREET, 
    avgWait: 20, 
    duration: 20, 
    x: 50, 
    y: 90,
    description: "Faites le tour du Parc Disneyland à bord d'un train à vapeur authentique pour une vue panoramique relaxante.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Disneyland_Railroad_Paris_City_Hall.jpg/640px-Disneyland_Railroad_Paris_City_Hall.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/disneyland-railroad/',
    reviewSummary: "Un incontournable pour se reposer et voir le parc sous un autre angle. Le charme du train à vapeur opère toujours."
  },
  { 
    id: 'dlp_main_2', 
    name: 'Main Street Vehicles', 
    park: Park.DISNEYLAND, 
    land: Land.MAIN_STREET, 
    avgWait: 10, 
    duration: 5, 
    x: 50, 
    y: 82,
    description: "Remontez le temps à bord d'une voiture ancienne, d'un omnibus ou d'un camion de pompiers du début du 20ème siècle.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Main_Street_Vehicles_DLP.jpg/640px-Main_Street_Vehicles_DLP.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/main-street-vehicles/',
    reviewSummary: "Sympa pour remonter Main Street sans marcher. Les conducteurs sont souvent drôles et l'ambiance rétro est top."
  },

  // --- FRONTIERLAND ---
  { 
    id: 'dlp_2', 
    name: 'Big Thunder Mountain', 
    park: Park.DISNEYLAND, 
    land: Land.FRONTIERLAND, 
    avgWait: 45, 
    duration: 4, 
    x: 20, 
    y: 60,
    description: "Le train de la mine le plus célèbre de l'Ouest ! Une montagne russe familiale palpitante au cœur d'une mine hantée.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Big_Thunder_Mountain_Paris_2013.jpg/640px-Big_Thunder_Mountain_Paris_2013.jpg',
    intensity: 'Sensations fortes',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/big-thunder-mountain/',
    reviewSummary: "Le meilleur train de la mine ! Les sensations sont là sans être trop violentes, et le passage sous l'eau est culte."
  },
  { 
    id: 'dlp_3', 
    name: 'Phantom Manor', 
    park: Park.DISNEYLAND, 
    land: Land.FRONTIERLAND, 
    avgWait: 20, 
    duration: 10, 
    x: 15, 
    y: 75,
    description: "Pénétrez dans ce manoir délabré où 999 fantômes vous attendent pour une visite mystérieuse et envoûtante.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Phantom_Manor_Disneyland_Paris_2012.jpg/640px-Phantom_Manor_Disneyland_Paris_2012.jpg',
    intensity: 'Modéré',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/phantom-manor/',
    reviewSummary: "L'ambiance est incroyable dès la file d'attente. Les effets spéciaux sont magnifiques et l'histoire captivante."
  },
  { 
    id: 'dlp_frontier_3', 
    name: 'Thunder Mesa Riverboat Landing', 
    park: Park.DISNEYLAND, 
    land: Land.FRONTIERLAND, 
    avgWait: 15, 
    duration: 15, 
    x: 30, 
    y: 65,
    description: "Embarquez pour une croisière majestueuse sur les rivières du Far West à bord d'un vieux bateau à aubes.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Molly_Brown_Riverboat_Disneyland_Paris.jpg/640px-Molly_Brown_Riverboat_Disneyland_Paris.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/thunder-mesa-riverboat-landing/',
    reviewSummary: "Une balade très apaisante avec de superbes vues inédites sur Big Thunder Mountain. Idéal pour faire une pause."
  },

  // --- ADVENTURELAND ---
  { 
    id: 'dlp_4', 
    name: 'Pirates of the Caribbean', 
    park: Park.DISNEYLAND, 
    land: Land.ADVENTURELAND, 
    avgWait: 25, 
    duration: 10, 
    x: 15, 
    y: 45,
    description: "Embarquez pour une croisière au temps des pirates, rythmée par la célèbre chanson 'Yo Ho, Yo Ho'.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Pirates_of_the_Caribbean_Disneyland_Paris_Entrance.jpg/640px-Pirates_of_the_Caribbean_Disneyland_Paris_Entrance.jpg',
    intensity: 'Modéré',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/pirates-of-the-caribbean/',
    reviewSummary: "L'immersion est totale, on a vraiment l'impression d'y être. La petite chute surprend toujours agréablement !"
  },
  { 
    id: 'dlp_5', 
    name: 'Indiana Jones™ et le Temple du Péril', 
    park: Park.DISNEYLAND, 
    land: Land.ADVENTURELAND, 
    avgWait: 30, 
    duration: 2, 
    x: 10, 
    y: 35,
    description: "Une aventure trépidante en wagonnet à travers des ruines antiques, incluant un looping impressionnant.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Indiana_Jones_et_le_Temple_du_P%C3%A9ril_03.jpg/640px-Indiana_Jones_et_le_Temple_du_P%C3%A9ril_03.jpg',
    intensity: 'Sensations fortes',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/indiana-jones-and-the-temple-of-peril/',
    reviewSummary: "Ça secoue beaucoup, attention aux oreilles ! Le looping est sympa mais le tour est vraiment très court."
  },
  { 
    id: 'dlp_adv_3', 
    name: 'La Cabane des Robinson', 
    park: Park.DISNEYLAND, 
    land: Land.ADVENTURELAND, 
    avgWait: 0, 
    duration: 15, 
    x: 25, 
    y: 45,
    description: "Grimpez au sommet de cet arbre gigantesque pour explorer la maison naufragée de la famille Suisse Robinson.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/La_Cabane_des_Robinson_Disneyland_Paris.jpg/640px-La_Cabane_des_Robinson_Disneyland_Paris.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/la-cabane-des-robinson/',
    reviewSummary: "Beaucoup de marches à monter, mais la vue en haut est imprenable. Les détails de la reconstitution sont bluffants."
  },
  { 
    id: 'dlp_adv_4', 
    name: 'Le Passage Enchanté d\'Aladdin', 
    park: Park.DISNEYLAND, 
    land: Land.ADVENTURELAND, 
    avgWait: 0, 
    duration: 10, 
    x: 20, 
    y: 40,
    description: "Une promenade à pied à travers des scènes miniatures recréant l'histoire d'Aladdin.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Le_Passage_Enchant%C3%A9_d%27Aladdin.jpg/640px-Le_Passage_Enchant%C3%A9_d%27Aladdin.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/le-passage-enchante-d-aladdin/',
    reviewSummary: "Petit parcours à pied très mignon, fait en 5 minutes. Les scènes miniatures sont jolies mais ce n'est pas incontournable."
  },
  
  // --- FANTASYLAND ---
  { 
    id: 'dlp_castle', 
    name: 'La Tanière du Dragon', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 0, 
    duration: 10, 
    x: 50, 
    y: 55,
    description: "Osez vous aventurer sous le Château pour réveiller un immense dragon audio-animatronic assoupi.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/La_Tani%C3%A8re_du_Dragon_Disneyland_Paris.jpg/640px-La_Tani%C3%A8re_du_Dragon_Disneyland_Paris.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/la-taniere-du-dragon/',
    reviewSummary: "Impressionnant de réalisme ! Il fait sombre et le dragon peut effrayer les tout-petits, mais c'est une pépite cachée."
  },
  { 
    id: 'dlp_6', 
    name: 'Peter Pan\'s Flight', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 50, 
    duration: 3, 
    x: 40, 
    y: 35,
    description: "Envolez-vous au-dessus des toits de Londres à bord d'un galion pirate magique direction le Pays Imaginaire.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Peter_Pan%27s_Flight_Disneyland_Paris_Entrance.jpg/640px-Peter_Pan%27s_Flight_Disneyland_Paris_Entrance.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/peter-pans-flight/',
    reviewSummary: "Absolument magique, la sensation de vol est unique. Dommage que ce soit si court pour autant d'attente."
  },
  { 
    id: 'dlp_7', 
    name: 'It\'s a small world', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 20, 
    duration: 10, 
    x: 65, 
    y: 25,
    description: "La croisière la plus joyeuse du monde ! Un voyage musical autour du globe avec des poupées chantantes.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/It%27s_a_Small_World_Disneyland_Paris_Facade.jpg/640px-It%27s_a_Small_World_Disneyland_Paris_Facade.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/its-a-small-world/',
    reviewSummary: "La musique reste dans la tête toute la journée ! C'est coloré, joyeux et assez long, parfait pour les enfants."
  },
  { 
    id: 'dlp_8', 
    name: 'Dumbo the Flying Elephant', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 30, 
    duration: 2, 
    x: 55, 
    y: 30,
    description: "Prenez de la hauteur à dos d'éléphant dans ce manège aérien classique qui ravira petits et grands.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Dumbo_the_Flying_Elephant_Disneyland_Paris_2011.jpg/640px-Dumbo_the_Flying_Elephant_Disneyland_Paris_2011.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/dumbo-the-flying-elephant/',
    reviewSummary: "Un grand classique qui offre une jolie vue sur Fantasyland. L'attente est souvent longue pour la durée du tour."
  },
  { 
    id: 'dlp_fan_4', 
    name: 'Blanche-Neige et les Sept Nains', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 25, 
    duration: 3, 
    x: 38, 
    y: 42,
    description: "Revivez l'histoire de Blanche-Neige dans un parcours scénique, mais attention à la méchante sorcière !",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Blanche-Neige_et_les_Sept_Nains_Disneyland_Paris_Entrance.jpg/640px-Blanche-Neige_et_les_Sept_Nains_Disneyland_Paris_Entrance.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/blanche-neige-et-les-sept-nains/',
    reviewSummary: "Un peu effrayant pour les très jeunes enfants à cause de la sorcière, mais très fidèle au dessin animé."
  },
  { 
    id: 'dlp_fan_5', 
    name: 'Les Voyages de Pinocchio', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 20, 
    duration: 3, 
    x: 42, 
    y: 42,
    description: "Accompagnez Pinocchio dans ses aventures mouvementées, de Stromboli à l'île aux plaisirs.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Les_Voyages_de_Pinocchio_Disneyland_Paris.jpg/640px-Les_Voyages_de_Pinocchio_Disneyland_Paris.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/les-voyages-de-pinocchio/',
    reviewSummary: "Similaire à Blanche-Neige, c'est un parcours rapide. Les décors sont jolis et l'histoire bien racontée."
  },
  { 
    id: 'dlp_fan_6', 
    name: 'Le Carrousel de Lancelot', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 15, 
    duration: 3, 
    x: 48, 
    y: 40,
    description: "Montez sur un magnifique cheval de bois dans ce carrousel royal classique au cœur de Fantasyland.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Le_Carrousel_de_Lancelot.jpg/640px-Le_Carrousel_de_Lancelot.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/le-carrousel-de-lancelot/',
    reviewSummary: "Magnifique surtout de nuit quand il est illuminé. Un moment de nostalgie pure pour petits et grands."
  },
  { 
    id: 'dlp_fan_7', 
    name: 'Mad Hatter\'s Tea Cups', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 20, 
    duration: 2, 
    x: 60, 
    y: 40,
    description: "Tournoyez à toute vitesse dans des tasses de thé géantes lors de la fête de non-anniversaire du Chapelier Fou.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Mad_Hatter%27s_Tea_Cups_Disneyland_Paris_Roof.jpg/640px-Mad_Hatter%27s_Tea_Cups_Disneyland_Paris_Roof.jpg',
    intensity: 'Modéré',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/mad-hatters-tea-cups/',
    reviewSummary: "Ça tourne très vite si on le veut ! Très drôle à faire en groupe pour voir qui résiste le mieux au tournis."
  },
  { 
    id: 'dlp_fan_8', 
    name: 'Alice\'s Curious Labyrinth', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 10, 
    duration: 15, 
    x: 62, 
    y: 35,
    description: "Perdez-vous dans le labyrinthe de la Reine de Cœur et profitez d'une vue imprenable depuis son château.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Alice%27s_Curious_Labyrinth_Castle_Disneyland_Paris.jpg/640px-Alice%27s_Curious_Labyrinth_Castle_Disneyland_Paris.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/alices-curious-labyrinth/',
    reviewSummary: "Super pour laisser courir les enfants. La vue depuis le château de la Reine de Cœur vaut le détour."
  },
  { 
    id: 'dlp_fan_9', 
    name: 'Casey Jr. - le Petit Train du Cirque', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 25, 
    duration: 3, 
    x: 65, 
    y: 30,
    description: "Un petit train rapide qui parcourt le Pays des Contes de Fées. Idéal pour les plus petits.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Casey_Jr._Le_Petit_Train_du_Cirque_Disneyland_Paris.jpg/640px-Casey_Jr._Le_Petit_Train_du_Cirque_Disneyland_Paris.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/casey-jr-le-petit-train-du-cirque/',
    reviewSummary: "Plus rapide qu'il n'en a l'air ! La musique est entraînante et le tour est sympa, même pour les adultes."
  },
  { 
    id: 'dlp_fan_10', 
    name: 'Le Pays des Contes de Fées', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 20, 
    duration: 10, 
    x: 68, 
    y: 32,
    description: "Une promenade en bateau paisible à travers des villages miniatures tirés des classiques Disney.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Le_Pays_des_Contes_de_F%C3%A9es_Disneyland_Paris_Castle.jpg/640px-Le_Pays_des_Contes_de_F%C3%A9es_Disneyland_Paris_Castle.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/le-pays-des-contes-de-fees/',
    reviewSummary: "Promenade en bateau très calme, parfaite pour se détendre. Les miniatures sont adorables et bien entretenues."
  },
  
  // --- DISCOVERYLAND ---
  { 
    id: 'dlp_9', 
    name: 'Star Wars™ Hyperspace Mountain', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 40, 
    duration: 2, 
    x: 85, 
    y: 50,
    description: "Rejoignez l'Alliance Rebelle pour une bataille épique dans l'espace à vitesse lumière.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Space_Mountain_Mission_2_Disneyland_Paris.jpg/640px-Space_Mountain_Mission_2_Disneyland_Paris.jpg',
    intensity: 'Sensations fortes',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/star-wars-hyperspace-mountain/',
    reviewSummary: "Très intense et rapide ! La musique Star Wars dans les oreilles rend l'expérience vraiment épique."
  },
  { 
    id: 'dlp_10', 
    name: 'Star Tours: L\'Aventure Continue', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 15, 
    duration: 5, 
    x: 90, 
    y: 60,
    description: "Un simulateur de vol 3D imprévisible à travers la galaxie Star Wars. Chaque voyage est unique !",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Star_Tours_Disneyland_Paris_X-Wing.jpg/640px-Star_Tours_Disneyland_Paris_X-Wing.jpg',
    intensity: 'Modéré',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/star-tours-l-aventure-continue/',
    reviewSummary: "Génial car l'histoire change à chaque fois. On ne s'ennuie jamais, et C-3PO est hilarant."
  },
  { 
    id: 'dlp_11', 
    name: 'Buzz Lightyear Laser Blast', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 35, 
    duration: 5, 
    x: 75, 
    y: 60,
    description: "Aidez Buzz l'Éclair à vaincre Zurg dans ce stand de tir laser interactif où vous marquez des points.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Buzz_Lightyear_Laser_Blast_Disneyland_Paris_Entrance.jpg/640px-Buzz_Lightyear_Laser_Blast_Disneyland_Paris_Entrance.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/buzz-lightyear-laser-blast/',
    reviewSummary: "Super fun pour défier ses amis et sa famille. Le système de points rend l'attraction très addictive !"
  },
  { 
    id: 'dlp_disc_4', 
    name: 'Autopia', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 25, 
    duration: 5, 
    x: 80, 
    y: 40,
    description: "Prenez le volant de votre propre voiture futuriste pour une balade sur une autoroute sinueuse.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Autopia_Disneyland_Paris_Track.jpg/640px-Autopia_Disneyland_Paris_Track.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/autopia/',
    reviewSummary: "Les enfants adorent conduire eux-mêmes. Le volant est un peu dur et ça sent l'essence, mais c'est un classique."
  },
  { 
    id: 'dlp_disc_5', 
    name: 'Orbitron', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 25, 
    duration: 2, 
    x: 75, 
    y: 50,
    description: "Pilotez votre propre vaisseau spatial rétro-futuriste et contrôlez votre altitude au milieu des planètes.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Orbitron_Disneyland_Paris_Night.jpg/640px-Orbitron_Disneyland_Paris_Night.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/orbitron/',
    reviewSummary: "Ça donne un peu le vertige ! La vue sur Discoveryland est top, surtout de nuit avec les néons."
  },
  { 
    id: 'dlp_disc_6', 
    name: 'Mickey et son Orchestre PhilharMagique', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 15, 
    duration: 12, 
    x: 68, 
    y: 48,
    description: "Une expérience cinéma 4D où Donald Duck vous plonge dans les plus grandes chansons Disney.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Discoveryland_Theatre_Disneyland_Paris.jpg/640px-Discoveryland_Theatre_Disneyland_Paris.jpg',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/mickeys-philharmagic/',
    reviewSummary: "Un film 4D très bien fait, on sent vraiment les odeurs et l'eau. Une excellente surprise souvent méconnue."
  },
];