import { Attraction, Park, Land } from './types';

export const USERS_LIST = [
  "Alexandre", "Apolline", "Benoît", "Camille", "Celeste", "Cécile",
  "Elisabeth", "Igor", "Izza", "Hamza", "Jean", "Leo", "Lucas",
  "Margot", "Marie", "Maxime", "Mina", "Nicolas", "Pernelle",
  "Raphaël", "Romain", "Ruben", "Sathasivam", "Tiphaine", "William"
];

export const WEATHER_FORECAST = [
  { hour: '09h', temp: '2°', condition: 'cloudy', icon: 'cloud' },
  { hour: '10h', temp: '3°', condition: 'cloudy', icon: 'cloud' },
  { hour: '11h', temp: '4°', condition: 'sunny', icon: 'sun' },
  { hour: '12h', temp: '6°', condition: 'sunny', icon: 'sun' },
  { hour: '13h', temp: '7°', condition: 'partly-cloudy', icon: 'cloud-sun' },
  { hour: '14h', temp: '7°', condition: 'partly-cloudy', icon: 'cloud-sun' },
  { hour: '15h', temp: '6°', condition: 'rainy', icon: 'cloud-rain' },
  { hour: '16h', temp: '5°', condition: 'rainy', icon: 'cloud-rain' },
  { hour: '17h', temp: '4°', condition: 'cloudy', icon: 'cloud' },
  { hour: '18h', temp: '3°', condition: 'clear', icon: 'moon' },
  { hour: '19h', temp: '2°', condition: 'clear', icon: 'moon' },
];

export const ATTRACTIONS: Attraction[] = [
  // --- MAIN STREET U.S.A. ---
  { 
    id: 'dlp_1', 
    name: 'Disneyland Railroad', 
    park: Park.DISNEYLAND, 
    land: Land.MAIN_STREET, 
    avgWait: 20, 
    duration: 20, 
    x: 50, 
    y: 85,
    description: "Faites le tour du Parc Disneyland à bord d'un train à vapeur authentique pour une vue panoramique relaxante.",
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/disneyland-railroad/'
  },
  { 
    id: 'dlp_main_2', 
    name: 'Main Street Vehicles', 
    park: Park.DISNEYLAND, 
    land: Land.MAIN_STREET, 
    avgWait: 10, 
    duration: 5, 
    x: 50, 
    y: 80,
    description: "Remontez le temps à bord d'une voiture ancienne, d'un omnibus ou d'un camion de pompiers du début du 20ème siècle.",
    imageUrl: 'https://images.unsplash.com/photo-1559564477-2e86595b814a?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/main-street-vehicles/'
  },

  // --- FRONTIERLAND ---
  { 
    id: 'dlp_2', 
    name: 'Big Thunder Mountain', 
    park: Park.DISNEYLAND, 
    land: Land.FRONTIERLAND, 
    avgWait: 45, 
    duration: 4, 
    x: 25, 
    y: 60,
    description: "Le train de la mine le plus célèbre de l'Ouest ! Une montagne russe familiale palpitante au cœur d'une mine hantée.",
    imageUrl: 'https://images.unsplash.com/photo-1533613220913-26228d18f216?auto=format&fit=crop&w=300&q=80',
    intensity: 'Sensations fortes',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/big-thunder-mountain/'
  },
  { 
    id: 'dlp_3', 
    name: 'Phantom Manor', 
    park: Park.DISNEYLAND, 
    land: Land.FRONTIERLAND, 
    avgWait: 20, 
    duration: 10, 
    x: 20, 
    y: 65,
    description: "Pénétrez dans ce manoir délabré où 999 fantômes vous attendent pour une visite mystérieuse et envoûtante.",
    imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=300&q=80',
    intensity: 'Modéré',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/phantom-manor/'
  },
  { 
    id: 'dlp_frontier_3', 
    name: 'Thunder Mesa Riverboat Landing', 
    park: Park.DISNEYLAND, 
    land: Land.FRONTIERLAND, 
    avgWait: 15, 
    duration: 15, 
    x: 30, 
    y: 60,
    description: "Embarquez pour une croisière majestueuse sur les rivières du Far West à bord d'un vieux bateau à aubes.",
    imageUrl: 'https://images.unsplash.com/photo-1605130284535-11dd9eedc58a?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/thunder-mesa-riverboat-landing/'
  },

  // --- ADVENTURELAND ---
  { 
    id: 'dlp_4', 
    name: 'Pirates of the Caribbean', 
    park: Park.DISNEYLAND, 
    land: Land.ADVENTURELAND, 
    avgWait: 25, 
    duration: 10, 
    x: 20, 
    y: 40,
    description: "Embarquez pour une croisière au temps des pirates, rythmée par la célèbre chanson 'Yo Ho, Yo Ho'.",
    imageUrl: 'https://images.unsplash.com/photo-1520065786657-b71a007dd8a5?auto=format&fit=crop&w=300&q=80',
    intensity: 'Modéré',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/pirates-of-the-caribbean/'
  },
  { 
    id: 'dlp_5', 
    name: 'Indiana Jones™ et le Temple du Péril', 
    park: Park.DISNEYLAND, 
    land: Land.ADVENTURELAND, 
    avgWait: 30, 
    duration: 2, 
    x: 15, 
    y: 35,
    description: "Une aventure trépidante en wagonnet à travers des ruines antiques, incluant un looping impressionnant.",
    imageUrl: 'https://images.unsplash.com/photo-1564357649322-c7ec935726df?auto=format&fit=crop&w=300&q=80',
    intensity: 'Sensations fortes',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/indiana-jones-and-the-temple-of-peril/'
  },
  { 
    id: 'dlp_adv_3', 
    name: 'La Cabane des Robinson', 
    park: Park.DISNEYLAND, 
    land: Land.ADVENTURELAND, 
    avgWait: 0, 
    duration: 15, 
    x: 25, 
    y: 45,
    description: "Grimpez au sommet de cet arbre gigantesque pour explorer la maison naufragée de la famille Suisse Robinson.",
    imageUrl: 'https://images.unsplash.com/photo-1501685532562-aa6846b14a0e?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/la-cabane-des-robinson/'
  },
  { 
    id: 'dlp_adv_4', 
    name: 'Le Passage Enchanté d\'Aladdin', 
    park: Park.DISNEYLAND, 
    land: Land.ADVENTURELAND, 
    avgWait: 0, 
    duration: 10, 
    x: 20, 
    y: 38,
    description: "Une promenade à pied à travers des scènes miniatures recréant l'histoire d'Aladdin.",
    imageUrl: 'https://images.unsplash.com/photo-1528041119984-da3a9f8d04d1?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/le-passage-enchante-d-aladdin/'
  },
  
  // --- FANTASYLAND ---
  { 
    id: 'dlp_castle', 
    name: 'La Tanière du Dragon', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 0, 
    duration: 10, 
    x: 50, 
    y: 55,
    description: "Osez vous aventurer sous le Château pour réveiller un immense dragon audio-animatronic assoupi.",
    imageUrl: 'https://images.unsplash.com/photo-1638628293219-c065073107b0?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/la-taniere-du-dragon/'
  },
  { 
    id: 'dlp_6', 
    name: 'Peter Pan\'s Flight', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 50, 
    duration: 3, 
    x: 45, 
    y: 45,
    description: "Envolez-vous au-dessus des toits de Londres à bord d'un galion pirate magique direction le Pays Imaginaire.",
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/peter-pans-flight/'
  },
  { 
    id: 'dlp_7', 
    name: 'It\'s a small world', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 20, 
    duration: 10, 
    x: 60, 
    y: 35,
    description: "La croisière la plus joyeuse du monde ! Un voyage musical autour du globe avec des poupées chantantes.",
    imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/its-a-small-world/'
  },
  { 
    id: 'dlp_8', 
    name: 'Dumbo the Flying Elephant', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 30, 
    duration: 2, 
    x: 50, 
    y: 40,
    description: "Prenez de la hauteur à dos d'éléphant dans ce manège aérien classique qui ravira petits et grands.",
    imageUrl: 'https://images.unsplash.com/photo-1550951298-5c7b95a66b21?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/dumbo-the-flying-elephant/'
  },
  { 
    id: 'dlp_fan_4', 
    name: 'Blanche-Neige et les Sept Nains', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 25, 
    duration: 3, 
    x: 42, 
    y: 45,
    description: "Revivez l'histoire de Blanche-Neige dans un parcours scénique, mais attention à la méchante sorcière !",
    imageUrl: 'https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/blanche-neige-et-les-sept-nains/'
  },
  { 
    id: 'dlp_fan_5', 
    name: 'Les Voyages de Pinocchio', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 20, 
    duration: 3, 
    x: 43, 
    y: 46,
    description: "Accompagnez Pinocchio dans ses aventures mouvementées, de Stromboli à l'île aux plaisirs.",
    imageUrl: 'https://images.unsplash.com/photo-1545887310-d1c0e9c2e87b?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/les-voyages-de-pinocchio/'
  },
  { 
    id: 'dlp_fan_6', 
    name: 'Le Carrousel de Lancelot', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 15, 
    duration: 3, 
    x: 48, 
    y: 48,
    description: "Montez sur un magnifique cheval de bois dans ce carrousel royal classique au cœur de Fantasyland.",
    imageUrl: 'https://images.unsplash.com/photo-1514314363460-4b36650d4226?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/le-carrousel-de-lancelot/'
  },
  { 
    id: 'dlp_fan_7', 
    name: 'Mad Hatter\'s Tea Cups', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 20, 
    duration: 2, 
    x: 55, 
    y: 45,
    description: "Tournoyez à toute vitesse dans des tasses de thé géantes lors de la fête de non-anniversaire du Chapelier Fou.",
    imageUrl: 'https://images.unsplash.com/photo-1576608605148-a7b73664df31?auto=format&fit=crop&w=300&q=80',
    intensity: 'Modéré',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/mad-hatters-tea-cups/'
  },
  { 
    id: 'dlp_fan_8', 
    name: 'Alice\'s Curious Labyrinth', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 10, 
    duration: 15, 
    x: 58, 
    y: 42,
    description: "Perdez-vous dans le labyrinthe de la Reine de Cœur et profitez d'une vue imprenable depuis son château.",
    imageUrl: 'https://images.unsplash.com/photo-1609707236995-4e57694cc07e?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/alices-curious-labyrinth/'
  },
  { 
    id: 'dlp_fan_9', 
    name: 'Casey Jr. - le Petit Train du Cirque', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 25, 
    duration: 3, 
    x: 62, 
    y: 30,
    description: "Un petit train rapide qui parcourt le Pays des Contes de Fées. Idéal pour les plus petits.",
    imageUrl: 'https://images.unsplash.com/photo-1515165592879-1849b88c43e9?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/casey-jr-le-petit-train-du-cirque/'
  },
  { 
    id: 'dlp_fan_10', 
    name: 'Le Pays des Contes de Fées', 
    park: Park.DISNEYLAND, 
    land: Land.FANTASYLAND, 
    avgWait: 20, 
    duration: 10, 
    x: 64, 
    y: 32,
    description: "Une promenade en bateau paisible à travers des villages miniatures tirés des classiques Disney.",
    imageUrl: 'https://images.unsplash.com/photo-1597939135393-97199df58556?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/le-pays-des-contes-de-fees/'
  },
  
  // --- DISCOVERYLAND ---
  { 
    id: 'dlp_9', 
    name: 'Star Wars™ Hyperspace Mountain', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 40, 
    duration: 2, 
    x: 75, 
    y: 50,
    description: "Rejoignez l'Alliance Rebelle pour une bataille épique dans l'espace à vitesse lumière.",
    imageUrl: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?auto=format&fit=crop&w=300&q=80',
    intensity: 'Sensations fortes',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/star-wars-hyperspace-mountain/'
  },
  { 
    id: 'dlp_10', 
    name: 'Star Tours: L\'Aventure Continue', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 15, 
    duration: 5, 
    x: 80, 
    y: 55,
    description: "Un simulateur de vol 3D imprévisible à travers la galaxie Star Wars. Chaque voyage est unique !",
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=300&q=80',
    intensity: 'Modéré',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/star-tours-l-aventure-continue/'
  },
  { 
    id: 'dlp_11', 
    name: 'Buzz Lightyear Laser Blast', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 35, 
    duration: 5, 
    x: 70, 
    y: 55,
    description: "Aidez Buzz l'Éclair à vaincre Zurg dans ce stand de tir laser interactif où vous marquez des points.",
    imageUrl: 'https://images.unsplash.com/photo-1563207153-f403bf289096?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/buzz-lightyear-laser-blast/'
  },
  { 
    id: 'dlp_disc_4', 
    name: 'Autopia', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 25, 
    duration: 5, 
    x: 75, 
    y: 45,
    description: "Prenez le volant de votre propre voiture futuriste pour une balade sur une autoroute sinueuse.",
    imageUrl: 'https://images.unsplash.com/photo-1548664686-2b3763403202?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/autopia/'
  },
  { 
    id: 'dlp_disc_5', 
    name: 'Orbitron', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 25, 
    duration: 2, 
    x: 72, 
    y: 52,
    description: "Pilotez votre propre vaisseau spatial rétro-futuriste et contrôlez votre altitude au milieu des planètes.",
    imageUrl: 'https://images.unsplash.com/photo-1632296457356-e630c34601d6?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/orbitron/'
  },
  { 
    id: 'dlp_disc_6', 
    name: 'Mickey’s PhilharMagic', 
    park: Park.DISNEYLAND, 
    land: Land.DISCOVERYLAND, 
    avgWait: 15, 
    duration: 12, 
    x: 68, 
    y: 48,
    description: "Une expérience cinéma 4D où Donald Duck vous plonge dans les plus grandes chansons Disney.",
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-71053e3e095c?auto=format&fit=crop&w=300&q=80',
    intensity: 'Calme',
    officialUrl: 'https://www.disneylandparis.com/fr-fr/attractions/parc-disneyland/mickeys-philharmagic/'
  },
];